---
# Remote directory path where to store the app config files
service_path: ~/rss_temple/

# PostgreSQL role name of the root/admin
postgres_admin_user: postgres

# PostgreSQL DB name of the DB
postgres_name: postgres

# PostgreSQL role name of the semi-limited role used by rss_temple
app_postgres_user: monk

# If you want your Docker services to be prefixed (as in, `rss_temple` -> `staging-rss_temple`), set this string
app_docker_service_prefix: ''

# Name of the local timezone for `tzdata`
timezone: UTC

# Are the services running in debug mode? Should be false in production, unless specifically needed
app_debug: false
