---
- name: Create custom HTML directory
  ansible.builtin.file:
    path: '{{ _rss_temple_web_app__absolute_service_path }}/custom_html'
    state: directory
    mode: '0755'

- ansible.builtin.include_role:
    name: common
    tasks_from: safe_template_overwrite
  loop:
    - name: docker-compose.yml
      template: templates/docker-compose.yml.j2
      dest: '{{ _rss_temple_web_app__absolute_service_path }}/docker-compose.yml'
    - name: config.json
      template: templates/config.json.j2
      dest: '{{ _rss_temple_web_app__absolute_service_path }}/config.json'
    - name: Caddyfile
      template: templates/Caddyfile.j2
      dest: '{{ _rss_temple_web_app__absolute_service_path }}/Caddyfile'
    - name: index.head.html
      template: templates/index.head.html.j2
      dest: '{{ _rss_temple_web_app__absolute_service_path }}/custom_html/index.head.html'
