---
- name: Get Absolute Service Path
  block:
    - ansible.builtin.command:
        cmd: pwd
        chdir: '{{ service_path }}'
      changed_when: false
      register: _pwd_ret

    - ansible.builtin.set_fact:
        absolute_service_path: '{{ _pwd_ret.stdout }}'
