---
- name: Get Absolute Service Path
  block:
    - ansible.builtin.command:
        cmd: pwd
        chdir: '{{ rss_temple_home__service_path }}'
      changed_when: false
      register: _rss_temple_home__pwd_ret

    - ansible.builtin.set_fact:
        _rss_temple_home__absolute_service_path: '{{ _rss_temple_home__pwd_ret.stdout }}'
