---
- name: Create Extra Vars file
  ansible.builtin.copy:
    dest: ~/rss-temple-home-extras.{{ ansible_date_time.iso8601_basic }}.yml
    mode: '0600'
    content: |
      {{  {
          "rss_temple_home__service_path": rss_temple_home__service_path,
          "rss_temple_home__app_docker_service_prefix": rss_temple_home__app_docker_service_prefix,
          "rss_temple_home__docker_version": rss_temple_home__docker_version,
          "rss_temple_home__app_url": rss_temple_home__app_url,
          "rss_temple_home__twitter_url": rss_temple_home__twitter_url,
          "rss_temple_home__facebook_url": rss_temple_home__facebook_url,
          "rss_temple_home__instagram_url": rss_temple_home__instagram_url,
          "rss_temple_home__og_title_prefix": rss_temple_home__og_title_prefix,
          "rss_temple_home__og_image_host": rss_temple_home__og_image_host,
          "rss_temple_home__og_url_host": rss_temple_home__og_url_host,
          "rss_temple_home__og_description": rss_temple_home__og_description,
        } | to_nice_yaml(explicit_start=True) }}
