---
- ansible.builtin.set_fact:
    _rss_temple_home__extras_dict: "{{ _rss_temple_home__extras_dict | default({}) | combine({item.key: item.value}) }}"
  loop: "{{ vars | dict2items }}"
  when: item.key is match('^rss_temple_home__')

- name: Create Extra Vars file
  ansible.builtin.copy:
    dest: ~/rss-temple-home-extras.{{ ansible_date_time.iso8601_basic }}.yml
    mode: '0600'
    content: '{{  _rss_temple_home__extras_dict | to_nice_yaml(explicit_start=True) }}'
