---
- name: Create Extra Vars file
  ansible.builtin.copy:
    dest: ~/rss-temple-home-extras.{{ ansible_date_time.iso8601_basic }}.yml
    mode: '0600'
    content: |
      {{  {
          "service_path": service_path,
          "app_docker_service_prefix": app_docker_service_prefix,
          "docker_version": docker_version,
          "app_url": app_url,
          "twitter_url": twitter_url,
          "facebook_url": facebook_url,
          "instagram_url": instagram_url,
          "og_title_prefix": og_title_prefix,
          "og_image_host": og_image_host,
          "og_url_host": og_url_host,
          "og_description": og_description,
        } | to_nice_yaml(explicit_start=True) }}
