---
- ansible.builtin.include_tasks: extras_file.yml

- name: Setup `{{ rss_temple_home__service_path }}/`
  ansible.builtin.file:
    path: '{{ rss_temple_home__service_path }}/'
    state: directory
    mode: '0775'

- ansible.builtin.include_tasks: _absolute_service_path.yml

- ansible.builtin.include_tasks: setup_config.yml

- name: Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: '{{ _rss_temple_home__absolute_service_path }}'
    pull: always
  become: true
