---
- ansible.builtin.include_role:
    name: common
    tasks_from: safe_template_overwrite
  loop:
    - name: docker-compose.yml
      template: templates/docker-compose.yml.j2
      dest: '{{ rss_temple_home__absolute_service_path }}/docker-compose.yml'
    - name: .env
      template: templates/.env.j2
      dest: '{{ rss_temple_home__absolute_service_path }}/.env'
    - name: Caddyfile
      template: templates/Caddyfile.j2
      dest: '{{ rss_temple_home__absolute_service_path }}/Caddyfile'
    - name: index.head.html
      template: templates/index.head.html.j2
      dest: '{{ rss_temple_home__absolute_service_path }}/index.head.html'
    - name: contact.head.html
      template: templates/contact.head.html.j2
      dest: '{{ rss_temple_home__absolute_service_path }}/contact.head.html'
    - name: privacy.head.html
      template: templates/privacy.head.html.j2
      dest: '{{ rss_temple_home__absolute_service_path }}/privacy.head.html'
    - name: tos.head.html
      template: templates/tos.head.html.j2
      dest: '{{ rss_temple_home__absolute_service_path }}/tos.head.html'
