---
- name: Create custom HTML directory
  ansible.builtin.file:
    path: '{{ _rss_temple_home__absolute_service_path }}/custom_html'
    state: directory
    mode: '0755'

- ansible.builtin.include_role:
    name: common
    tasks_from: safe_template_overwrite
  loop:
    - name: docker-compose.yml
      template: templates/docker-compose.yml.j2
      dest: '{{ _rss_temple_home__absolute_service_path }}/docker-compose.yml'
    - name: .env
      template: templates/.env.j2
      dest: '{{ _rss_temple_home__absolute_service_path }}/.env'
    - name: Caddyfile
      template: templates/Caddyfile.j2
      dest: '{{ _rss_temple_home__absolute_service_path }}/Caddyfile'
    - name: index.head.html
      template: templates/index.head.html.j2
      dest: '{{ _rss_temple_home__absolute_service_path }}/custom_html/index.head.html'
    - name: contact.head.html
      template: templates/contact.head.html.j2
      dest: '{{ _rss_temple_home__absolute_service_path }}/custom_html/contact.head.html'
    - name: privacy.head.html
      template: templates/privacy.head.html.j2
      dest: '{{ _rss_temple_home__absolute_service_path }}/custom_html/privacy.head.html'
    - name: tos.head.html
      template: templates/tos.head.html.j2
      dest: '{{ _rss_temple_home__absolute_service_path }}/custom_html/tos.head.html'
