---
- ansible.builtin.include_role:
    name: murrple_1.rss_temple.common
    tasks_from: extras_file
  vars:
    common__extras_var_prefix: pre_rss_temple__
    common__extras_file_prefix: pre-rss-temple-extras

- ansible.builtin.assert:
    that: ansible_os_family in ('Debian', 'RedHat')
    fail_msg: "Unsupported OS family '{{ ansible_os_family }}' ({{ ansible_distribution }}); only Debian- and Red Hat-based hosts are supported"

- ansible.builtin.include_role:
    name: murrple_1.rss_temple.common
    tasks_from: service_dir
  vars:
    common__service_path: '{{ pre_rss_temple__service_path }}'

- name: Dependencies (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: dependencies__debian.yml

- name: Dependencies (Red Hat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.include_tasks: dependencies__red_hat.yml

- name: Setup Umask
  ansible.builtin.blockinfile:
    path: '{{ item }}'
    block: |
      umask 027
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Umask'
  register: _pre_rss_temple__aliases_blockinfile_ret
  failed_when: _pre_rss_temple__aliases_blockinfile_ret.failed and _pre_rss_temple__aliases_blockinfile_ret.rc != 257
  loop:
    - ~/.bashrc
    - ~/.profile
    - ~/.bash_profile

- ansible.builtin.include_tasks: _absolute_service_path.yml

- ansible.builtin.include_tasks: setup_config.yml

- name: Setup global Docker network
  community.docker.docker_network:
    name: global_rss_temple_net
    internal: true
  become: true

- name: Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: '{{ _pre_rss_temple__absolute_service_path }}'
    pull: always
  become: true

- name: Firewall (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: firewall__debian.yml

- name: Firewall (Red Hat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.include_tasks: firewall__red_hat.yml

- name: Papertrail
  when: pre_rss_temple__papertrail_destination_host | length > 0
  ansible.builtin.include_tasks: papertrail.yml
