galaxy_info:
  author: Murray Christopherson
  description: Deploy RSS Temple
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    versions:
    - 22.04

  galaxy_tags:
    - RSS

dependencies: []
