---
- ansible.builtin.include_vars: dependencies__debian.yml

- name: Download Docker's `apt` key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Install Docker's `apt` repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ [ansible_architecture] | map('extract', _pre_rss_temple__deb_architecture) | first }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable # noqa yaml[line-length]
    state: present
    filename: docker

- name: Install dependencies via `apt`
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-pip
      - ufw
    state: present
    update_cache: true

- name: Add `{{ ansible_user }}` to `docker` group
  when: pre_rss_temple__should_add_ansible_user_to_docker_group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    append: true
    groups: docker
