---
- ansible.builtin.set_fact:
    _pre_rss_temple__extras_dict: "{{ _pre_rss_temple__extras_dict | default({}) | combine({item.key: item.value}) }}"
  loop: "{{ vars | dict2items }}"
  when: item.key is match('^pre_rss_temple__')

- name: Create Extra Vars file
  ansible.builtin.copy:
    dest: ~/pre-rss-temple-extras.{{ ansible_date_time.iso8601_basic }}.yml
    mode: '0600'
    content: '{{  _pre_rss_temple__extras_dict | to_nice_yaml(explicit_start=True) }}'
