---
- ansible.builtin.include_tasks: extras_file.yml

- ansible.builtin.stat:
    path: "{{ pre_rss_temple__repo_path | regex_replace('/$', '') | dirname }}"
  register: _pre_rss_temple__repo_parent_stat

- ansible.builtin.fail:
    msg: |
      Git repo parent directory '{{ pre_rss_temple__repo_path | regex_replace('/$', '') | dirname }}' is not writable by the current user.
      This needs to handled manually, as its handling is dependant on if the directory is to be considered
      a user directory (like a home directory) or a system directory (like `/opt/*`).
      Specifically, we don't want to (re)set the "group" and "sticky bit" on a user directory, but we probably
      want to set those things on a system directory.
  when: not _pre_rss_temple__repo_parent_stat.stat.writeable | default(false)

- name: Dependencies (Debian)
  when: ansible_distribution in ('Debian', 'Ubuntu')
  ansible.builtin.include_tasks: dependencies__debian.yml

- name: Dependencies (Red Hat)
  when: ansible_distribution in ('CentOS', 'Red Hat Enterprise Linux', 'Rocky')
  ansible.builtin.include_tasks: dependencies__red_hat.yml

- name: Setup Umask
  ansible.builtin.blockinfile:
    path: '{{ item }}'
    block: |
      umask 027
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Umask'
  register: _pre_rss_temple__aliases_blockinfile_ret
  failed_when: _pre_rss_temple__aliases_blockinfile_ret.failed and _pre_rss_temple__aliases_blockinfile_ret.rc != 257
  loop:
    - ~/.bashrc
    - ~/.profile
    - ~/.bash_profile

- name: Setup `{{ pre_rss_temple__service_path }}/`
  ansible.builtin.file:
    path: '{{ pre_rss_temple__service_path }}/'
    state: directory
    mode: '0775'

- ansible.builtin.include_tasks: _absolute_service_path.yml

- ansible.builtin.include_tasks: setup_config.yml

- name: Setup global Docker network
  community.docker.docker_network:
    name: global_rss_temple_net
    internal: true
  become: true

- name: Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: '{{ _pre_rss_temple__absolute_service_path }}'
    pull: always
  become: true

- name: Firewall (Ubuntu)
  when: ansible_distribution in ('Debian', 'Ubuntu')
  ansible.builtin.include_tasks: firewall__debian.yml

- name: Firewall (Red Hat)
  when: ansible_distribution in ('CentOS', 'Red Hat Enterprise Linux', 'Rocky')
  ansible.builtin.include_tasks: firewall__red_hat.yml

- name: Papertrail
  ansible.builtin.include_tasks: papertrail.yml
