---
- ansible.builtin.include_tasks: extras_file.yml

- name: Dependencies (Debian)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.include_tasks: dependencies__debian.yml

- name: Dependencies (Red Hat)
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Rocky'
  ansible.builtin.include_tasks: dependencies__red_hat.yml

- name: Dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Setup `{{ pre_rss_temple__service_path }}/`
  ansible.builtin.file:
    path: '{{ pre_rss_temple__service_path }}/'
    state: directory
    mode: '0775'

- ansible.builtin.include_tasks: _absolute_service_path.yml

- ansible.builtin.include_tasks: setup_config.yml

- name: Setup global Docker network
  community.docker.docker_network:
    name: global_rss_temple_net
    internal: true
  become: true

- name: Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: '{{ _pre_rss_temple__absolute_service_path }}'
    pull: always
  become: true

- name: Firewall (Ubuntu)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.include_tasks: firewall__debian.yml

- name: Firewall (Red Hat)
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Rocky'
  ansible.builtin.include_tasks: firewall__red_hat.yml

- name: Papertrail
  ansible.builtin.include_tasks: papertrail.yml
