---
- ansible.builtin.include_role:
    name: common
    tasks_from: safe_template_overwrite
  loop:
    - name: docker-compose.yml
      template: templates/docker-compose.yml.j2
      dest: '{{ _pre_rss_temple__absolute_service_path }}/docker-compose.yml'
    - name: Caddyfile
      template: templates/Caddyfile.j2
      dest: '{{ _pre_rss_temple__absolute_service_path }}/Caddyfile'
