---
- ansible.builtin.include_role:
    name: common
    tasks_from: safe_template_overwrite
  loop:
    - name: docker-compose.yml
      template: templates/docker-compose.yml.j2
      dest: '{{ absolute_service_path }}/docker-compose.yml'
    - name: config.json
      template: templates/config.json.j2
      dest: '{{ absolute_service_path }}/config.json'

- ansible.builtin.include_role:
    name: common
    tasks_from: safe_file_overwrite
  loop:
    - name: Caddyfile
      src: files/Caddyfile
      dest: '{{ absolute_service_path }}/Caddyfile'
