---
- name: Restart Docker Service
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
  listen:
    - firewall changed

- name: Restart rsyslog Service
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  listen:
    - rsyslog changed
