---
- name: Get Get Absolute Service Path
  block:
    - ansible.builtin.command:
        cmd: pwd
        chdir: '{{ rss_temple__service_path }}'
      changed_when: false
      register: _pwd_ret

    - ansible.builtin.set_fact:
        rss_temple__absolute_service_path: '{{ _pwd_ret.stdout }}'
