---
- name: Create Extra Vars file
  ansible.builtin.copy:
    dest: ~/rss-temple-extras.{{ ansible_date_time.iso8601_basic }}.yml
    mode: '0600'
    content: |
      {{  {
          "rss_temple__service_path": rss_temple__service_path,
          "rss_temple__postgres_admin_user": rss_temple__postgres_admin_user,
          "rss_temple__postgres_name": rss_temple__postgres_name,
          "rss_temple__app_postgres_user": rss_temple__app_postgres_user,
          "rss_temple__app_docker_service_prefix": rss_temple__app_docker_service_prefix,
          "rss_temple__timezone": rss_temple__timezone,
          "rss_temple__app_debug": rss_temple__app_debug,
          "rss_temple__docker_version": rss_temple__docker_version,
          "rss_temple__postgres_admin_password": rss_temple__postgres_admin_password,
          "rss_temple__app_postgres_password": rss_temple__app_postgres_password,
          "rss_temple__app_superuser_email": rss_temple__app_superuser_email,
          "rss_temple__app_superuser_password": rss_temple__app_superuser_password,
          "rss_temple__app_secret_key": rss_temple__app_secret_key,
          "rss_temple__app_email_host": rss_temple__app_email_host,
          "rss_temple__app_email_port": rss_temple__app_email_port,
          "rss_temple__app_email_host_user": rss_temple__app_email_host_user,
          "rss_temple__app_email_host_password": rss_temple__app_email_host_password,
          "rss_temple__app_email_use_tls": rss_temple__app_email_use_tls,
          "rss_temple__app_email_use_ssl": rss_temple__app_email_use_ssl,
          "rss_temple__app_email_timeout": rss_temple__app_email_timeout,
          "rss_temple__app_default_from_email": rss_temple__app_default_from_email,
          "rss_temple__app_site_domain": rss_temple__app_site_domain,
          "rss_temple__app_site_name": rss_temple__app_site_name,
          "rss_temple__app_google_client_id": rss_temple__app_google_client_id,
          "rss_temple__app_google_secret": rss_temple__app_google_secret,
          "rss_temple__app_facebook_client_id": rss_temple__app_facebook_client_id,
          "rss_temple__app_facebook_secret": rss_temple__app_facebook_secret,
          "rss_temple__app_account_confirm_email_url": rss_temple__app_account_confirm_email_url,
          "rss_temple__app_account_email_verification_sent_url": rss_temple__app_account_email_verification_sent_url,
          "rss_temple__app_password_confirm_reset_url_format": rss_temple__app_password_confirm_reset_url_format,
          "rss_temple__app_social_connections_url": rss_temple__app_social_connections_url,
          "rss_temple__app_social_signup_url": rss_temple__app_social_signup_url,
        } | to_nice_yaml(explicit_start=True) }}
