---
- name: Calculate Gunicorn worker count
  when: rss_temple__gunicorn_workers is undefined
  ansible.builtin.set_fact:
    # The number of Gunicorn worker processes for handling requests. See https://docs.gunicorn.org/en/stable/settings.html#workers
    rss_temple__gunicorn_workers: '{{ ansible_processor_cores + 1 }}'

- name: Calculate Gunicorn thread count
  when: rss_temple__gunicorn_threads is undefined
  ansible.builtin.set_fact:
    # The number of Gunicorn threads for handling requests. See https://docs.gunicorn.org/en/stable/settings.html#threads
    rss_temple__gunicorn_threads: 2

- ansible.builtin.include_tasks: extras_file.yml

- name: Setup `{{ rss_temple__service_path }}/`
  ansible.builtin.file:
    path: '{{ rss_temple__service_path }}/overrides/'
    state: directory
    mode: '0775'

- ansible.builtin.include_tasks: _absolute_service_path.yml

- name: Setup `overrides/`
  ansible.builtin.file:
    path: '{{ _rss_temple__absolute_service_path }}/overrides/'
    state: directory
    mode: '0775'

- ansible.builtin.include_tasks: setup_config.yml

- name: Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: '{{ _rss_temple__absolute_service_path }}'
    pull: always
  become: true
  notify:
    - docker compose up'd

- ansible.builtin.meta: flush_handlers

- name: Setup PostgreSQL User
  ansible.builtin.import_tasks: app_postgres_user.yml

- name: Initial App Setup
  ansible.builtin.import_tasks: initial_app_setup.yml
