---
- ansible.builtin.include_role:
    name: common
    tasks_from: safe_template_overwrite
  loop:
    - name: docker-compose.yml
      template: templates/docker-compose.yml.j2
      dest: '{{ _rss_temple__absolute_service_path }}/docker-compose.yml'
    - name: .env
      template: templates/.env.j2
      dest: '{{ _rss_temple__absolute_service_path }}/.env'
    - name: Caddyfile
      template: templates/Caddyfile.j2
      dest: '{{ _rss_temple__absolute_service_path }}/Caddyfile'
    - name: overrides/local_settings.py
      template: templates/local_settings.py.j2
      dest: '{{ _rss_temple__absolute_service_path }}/overrides/local_settings.py'
    - name: schedulerdaemon.json
      template: templates/schedulerdaemon.json.j2
      dest: '{{ _rss_temple__absolute_service_path }}/schedulerdaemon.json'

- ansible.builtin.include_role:
    name: common
    tasks_from: safe_file_overwrite
  loop:
    - name: gunicorn.conf.py
      src: files/gunicorn.conf.py
      dest: '{{ _rss_temple__absolute_service_path }}/overrides/gunicorn.conf.py'
