---
- name: Prepare server to host some/all the RSS Temple subprojects
  hosts: all

  vars_prompt:
    - name: pre_rss_temple__papertrail_destination_host
      prompt: Papertrail Destination Host (ie 'logsN.papertrailapp.com')

    - name: pre_rss_temple__papertrail_destination_port
      prompt: Papertrail Destination Port

  roles:
    - pre_rss_temple
