---
- name: Setup Config (pre-rss-temple)
  hosts: all

  vars_prompt:
    - name: pre_rss_temple__ca_email
      prompt: Email (for creating an ACME account with your CA)
      private: false

  tasks:
    - ansible.builtin.include_role:
        name: pre_rss_temple
        tasks_from: _absolute_service_path
        public: true

    - ansible.builtin.include_role:
        name: pre_rss_temple
        tasks_from: setup_config
