---
- name: Setup Config (Home)
  hosts: all

  vars_prompt:
    - name: docker_version
      prompt: Docker tag name
      default: latest
      private: false

  tasks:
    - ansible.builtin.include_role:
        name: rss_temple_home
        tasks_from: _absolute_service_path
        public: true

    - ansible.builtin.include_role:
        name: rss_temple_home
        tasks_from: setup_config
