---
- name: Setup Config (App)
  hosts: all

  vars_prompt:
    - name: docker_version
      prompt: Docker tag name
      default: latest
      private: false

    - name: og_image
      prompt: URL for the OpenGraph image
      default: https://app.rsstemple.com/assets/images/og_image.jpg

    - name: og_url
      prompt: URL for the OpenGraph URL
      default: https://app.rsstemple.com

  tasks:
    - ansible.builtin.include_role:
        name: rss_temple_app
        tasks_from: _absolute_service_path
        public: true

    - ansible.builtin.include_role:
        name: rss_temple_app
        tasks_from: setup_config
