---
- name: Setup Config (Home)
  hosts: all

  vars_prompt:
    - name: docker_version
      prompt: Docker tag name
      default: latest
      private: false

    - name: og_image_host
      prompt: Hostname for the OpenGraph image (formatted to "<HOSTNAME>/media/og_image.png")
      default: https://rsstemple.com

    - name: og_url_host
      prompt: Hostname for the OpenGraph URL (formatted similar to "<HOSTNAME>/contact.html")
      default: https://rsstemple.com

  tasks:
    - ansible.builtin.include_role:
        name: rss_temple_home
        tasks_from: _absolute_service_path
        public: true

    - ansible.builtin.include_role:
        name: rss_temple_home
        tasks_from: setup_config
